name: Build

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Please update the test workflow cross-compile matrix when adding a new
        # target here.
        target: [
          aarch64-linux-android,
          arm-linux-androideabi,
          armv7-linux-androideabi,
          x86_64-unknown-linux-musl,
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - run: |
          export RUSTFLAGS='--cfg has_procmap_query_ioctl'
          cmd="cargo bench --bench=main --no-run --features=dont-generate-unit-test-files"
          ${cmd}
          bin=$(${cmd} 2>&1 | grep Executable | sed 's@.*(\(.*\))@\1@')
          mkdir -p bin
          mv "${bin}" bin/benches
      - uses: actions/upload-artifact@v4
        with:
          name: benches-${{ matrix.target }}
          path: bin/benches
